name: githubacdd
on: workflow_dispatch
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: print hello
        run: echo "hello srh"
      - name: print hi
        run: echo "hi new team"
